local store = require("review.store")

describe("review.store", function()
  before_each(function()
    store.clear()
  end)

  describe("add", function()
    it("creates a comment with generated id", function()
      local comment = store.add("file.lua", 10, "issue", "Fix this")
      assert.is_not_nil(comment.id)
      assert.equals("file.lua", comment.file)
      assert.equals(10, comment.line)
      assert.equals("issue", comment.type)
      assert.equals("Fix this", comment.text)
    end)

    it("stores comments by file", function()
      store.add("a.lua", 1, "note", "Note 1")
      store.add("a.lua", 2, "note", "Note 2")
      store.add("b.lua", 1, "issue", "Issue 1")

      assert.equals(2, #store.get_for_file("a.lua"))
      assert.equals(1, #store.get_for_file("b.lua"))
    end)
  end)

  describe("get_at_line", function()
    it("returns comment at specific line", function()
      store.add("file.lua", 10, "issue", "At line 10")
      store.add("file.lua", 20, "note", "At line 20")

      local comment = store.get_at_line("file.lua", 10)
      assert.is_not_nil(comment)
      assert.equals("At line 10", comment.text)
    end)

    it("returns nil when no comment at line", function()
      store.add("file.lua", 10, "issue", "At line 10")
      assert.is_nil(store.get_at_line("file.lua", 15))
    end)
  end)

  describe("update", function()
    it("updates comment text", function()
      local comment = store.add("file.lua", 10, "issue", "Original")
      local success = store.update(comment.id, "Updated")

      assert.is_true(success)
      assert.equals("Updated", store.get(comment.id).text)
    end)

    it("returns false for non-existent id", function()
      assert.is_false(store.update("fake_id", "text"))
    end)
  end)

  describe("delete", function()
    it("removes comment", function()
      local comment = store.add("file.lua", 10, "issue", "Delete me")
      assert.equals(1, store.count())

      local success = store.delete(comment.id)
      assert.is_true(success)
      assert.equals(0, store.count())
    end)

    it("returns false for non-existent id", function()
      assert.is_false(store.delete("fake_id"))
    end)
  end)

  describe("get_all", function()
    it("returns all comments sorted by file and line", function()
      store.add("b.lua", 20, "note", "B20")
      store.add("a.lua", 10, "note", "A10")
      store.add("a.lua", 5, "note", "A5")

      local all = store.get_all()
      assert.equals(3, #all)
      assert.equals("A5", all[1].text)
      assert.equals("A10", all[2].text)
      assert.equals("B20", all[3].text)
    end)
  end)

  describe("count", function()
    it("returns total comment count", function()
      assert.equals(0, store.count())
      store.add("a.lua", 1, "note", "1")
      store.add("b.lua", 1, "note", "2")
      assert.equals(2, store.count())
    end)
  end)

  describe("side awareness", function()
    it("stores side field on add", function()
      local c = store.add("file.lua", 10, "note", "old side", nil, "old")
      assert.equals("old", c.side)
    end)

    it("defaults side to new", function()
      local c = store.add("file.lua", 10, "note", "no side")
      assert.equals("new", c.side)
    end)

    it("get_at_line filters by side", function()
      store.add("file.lua", 10, "note", "old comment", nil, "old")
      store.add("file.lua", 10, "issue", "new comment", nil, "new")

      local old = store.get_at_line("file.lua", 10, "old")
      assert.is_not_nil(old)
      assert.equals("old comment", old.text)

      local new = store.get_at_line("file.lua", 10, "new")
      assert.is_not_nil(new)
      assert.equals("new comment", new.text)
    end)

    it("get_at_line without side returns first match", function()
      store.add("file.lua", 10, "note", "old comment", nil, "old")
      local c = store.get_at_line("file.lua", 10)
      assert.is_not_nil(c)
      assert.equals("old comment", c.text)
    end)

    it("get_overlapping filters by side", function()
      store.add("file.lua", 5, "note", "old range", 15, "old")
      store.add("file.lua", 5, "issue", "new range", 15, "new")

      local old = store.get_overlapping("file.lua", 8, 12, "old")
      assert.is_not_nil(old)
      assert.equals("old range", old.text)

      local new = store.get_overlapping("file.lua", 8, 12, "new")
      assert.is_not_nil(new)
      assert.equals("new range", new.text)
    end)

    it("get_for_file filters by side", function()
      store.add("file.lua", 5, "note", "old", nil, "old")
      store.add("file.lua", 10, "issue", "new", nil, "new")

      local old_comments = store.get_for_file("file.lua", "old")
      assert.equals(1, #old_comments)
      assert.equals("old", old_comments[1].text)

      local new_comments = store.get_for_file("file.lua", "new")
      assert.equals(1, #new_comments)
      assert.equals("new", new_comments[1].text)
    end)

    it("get_for_file without side returns all", function()
      store.add("file.lua", 5, "note", "old", nil, "old")
      store.add("file.lua", 10, "issue", "new", nil, "new")

      local all = store.get_for_file("file.lua")
      assert.equals(2, #all)
    end)

    it("get_for_file with side includes file-level comments", function()
      store.add("file.lua", 0, "note", "file comment")
      store.add("file.lua", 10, "issue", "new side", nil, "new")
      store.add("file.lua", 10, "note", "old side", nil, "old")

      local old_comments = store.get_for_file("file.lua", "old")
      assert.equals(2, #old_comments)

      local new_comments = store.get_for_file("file.lua", "new")
      assert.equals(2, #new_comments)
    end)

    it("comments on different sides at same line don't conflict", function()
      store.add("file.lua", 10, "note", "old note", nil, "old")
      store.add("file.lua", 10, "issue", "new issue", nil, "new")

      local old = store.get_at_line("file.lua", 10, "old")
      local new = store.get_at_line("file.lua", 10, "new")
      assert.is_not_nil(old)
      assert.is_not_nil(new)
      assert.are_not.equal(old.text, new.text)
    end)
  end)
end)
